"use strict";

/* UnionLedger — sandbox-safe vanilla JS. */
const VILLAGES=["Obodo Union","Umuahia Union","Umueze Union","Umunze Union","Osumenyi Union","Agulu Union","Nnewi Union","Awka Union","Orlu Union","Nsukka Union"];
const DEFAULT_LEVIES=[
 {id:"annual-dues",name:"Annual Dues",amount:25000,mandatory:true,active:true},
 {id:"burial-levy",name:"Burial Levy",amount:10000,mandatory:false,active:true},
 {id:"life-insurance",name:"Life Insurance Levy",amount:5000,mandatory:false,active:true},
 {id:"party-donation",name:"Party Donation",amount:0,mandatory:false,active:true},
 {id:"support-levy",name:"Support Levy",amount:5000,mandatory:false,active:true}
];
const KEYS={members:"ul_members_v2",requests:"ul_requests_v2",attendance:"ul_attendance_v2",transactions:"ul_transactions_v2",expenses:"ul_expenses_v2",audit:"ul_audit_v2",session:"ul_session_v2",levies:"ul_levies_v2",admins:"ul_admins_v2"};
const MASTER={id:"ADMIN-001",password:"Admin@123",name:"Union Administrator",role:"admin",village:"Obodo Union",master:true};
const mem=Object.create(null);
const storage=(()=>{try{const s=window.localStorage,p="__ul_probe__";s.setItem(p,"1");s.removeItem(p);return s;}catch(_){return {getItem:k=>Object.prototype.hasOwnProperty.call(mem,k)?mem[k]:null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k]};}})();
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const now=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
const money=n=>`₦${Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateOnly=v=>new Date(v).toLocaleDateString("en-NG",{day:"2-digit",month:"short",year:"numeric"});
const dateTime=v=>new Date(v).toLocaleString("en-NG",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"});
const norm=v=>String(v||"").trim().replace(/\s+/g," ").toLowerCase();
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function read(k,f=[]){try{const v=storage.getItem(k);return v?JSON.parse(v):f}catch(_){return f}}
function write(k,v){try{storage.setItem(k,JSON.stringify(v))}catch(_){}
}
function toast(t,m,type="success"){const x=$("#toast");if(!x)return;$("#toastTitle").textContent=t;$("#toastMessage").textContent=m;x.classList.toggle("error",type==="error");x.classList.add("show");clearTimeout(window.__ult);window.__ult=setTimeout(()=>x.classList.remove("show"),3600)}
function session(){return read(KEYS.session,null)}
function setSession(v){v?write(KEYS.session,v):storage.removeItem(KEYS.session)}
function audit(action,detail,meta={}){const s=session()||MASTER;const rows=read(KEYS.audit);rows.unshift({id:uid("AUD"),action,detail,adminId:s.id,adminName:s.name,at:now(),village:s.village,...meta});write(KEYS.audit,rows)}
function activeLevy(){return read(KEYS.levies,DEFAULT_LEVIES).filter(x=>x.active)}
function seed(){
 if(!storage.getItem(KEYS.levies))write(KEYS.levies,DEFAULT_LEVIES);
 if(!storage.getItem(KEYS.members))write(KEYS.members,[
  {id:"UO-0001",name:"Chinedu Okafor",phone:"08030000001",village:"Obodo Union",password:"Member@123",active:true,verified:true,createdAt:now()},
  {id:"UO-0002",name:"Emeka Nwosu",phone:"08030000002",village:"Obodo Union",password:"Member@456",active:true,verified:true,createdAt:now()},
  {id:"UM-0001",name:"Ngozi Eze",phone:"08030000003",village:"Umuahia Union",password:"Member@789",active:true,verified:true,createdAt:now()}
 ]);
 if(!storage.getItem(KEYS.admins))write(KEYS.admins,[MASTER]);
 [KEYS.requests,KEYS.attendance,KEYS.transactions,KEYS.expenses,KEYS.audit].forEach(k=>{if(!storage.getItem(k))write(k,[])})
}
function fillVillages(){["#loginVillage","#regVillage"].forEach(s=>{const e=$(s);if(e)e.innerHTML='<option value="">Select village union</option>'+VILLAGES.map(v=>`<option>${esc(v)}</option>`).join("")})}
function openAuth(mode="member"){const m=$("#authModal");if(!m)return;m.classList.add("open");m.setAttribute("aria-hidden","false");setAuthTab("login");$("#loginId").value=mode==="admin"?MASTER.id:"";$("#loginVillage").value=mode==="admin"?MASTER.village:"";$("#loginTitle").textContent=mode==="admin"?"Administrator access":"Welcome back";$("#loginSubtitle").textContent=mode==="admin"?"Sign in to manage your assigned village.":"Sign in to your village union account."}
function closeAuth(){$("#authModal")?.classList.remove("open")}
function openApp(){$("#appModal")?.classList.add("open")}
function closeApp(){$("#appModal")?.classList.remove("open")}
function setAuthTab(tab){const login=tab==="login";$("#loginPanel").hidden=!login;$("#registerPanel").hidden=login;$$('[data-auth-tab]').forEach(b=>b.classList.toggle("active",b.dataset.authTab===tab))}
function login(e){e.preventDefault();const village=$("#loginVillage").value,id=$("#loginId").value.trim(),pw=$("#loginPassword").value;if(!village){toast("Village required","Select the village assigned to this login.","error");return}
 const admins=read(KEYS.admins);const a=admins.find(x=>x.id.toLowerCase()===id.toLowerCase()&&x.password===pw&&x.active&&x.village===village);if(a){setSession({id:a.id,name:a.name,role:"admin",village:a.village,master:!!a.master});closeAuth();renderAdmin();openApp();toast("Welcome",`${a.name} · ${a.village}`);return}
 const m=read(KEYS.members).find(x=>x.id.toLowerCase()===id.toLowerCase()&&x.password===pw&&x.active&&x.verified&&x.village===village);if(!m){toast("Sign in failed","The ID, password and village must match exactly.","error");return}setSession({id:m.id,name:m.name,role:"member",village:m.village});closeAuth();renderMember();openApp();toast("Welcome back",`${m.name} · ${m.village}`)}
function registerMember(e){e.preventDefault();const village=$("#regVillage").value,name=$("#regFullName").value.trim(),phone=$("#regPhone").value.trim(),memberNo=$("#regMemberNo").value.trim(),note=$("#regNote").value.trim();if(!village||!name||!phone){toast("Incomplete request","Complete the required fields.","error");return}
 const members=read(KEYS.members);const existing=members.find(m=>m.village===village&&norm(m.name)===norm(name));if(existing){toast("Already a member","You are already a member, sign in with your login details or contact admin.","error");return}
 const requests=read(KEYS.requests);const duplicate=requests.find(r=>r.village===village&&norm(r.name)===norm(name)&&["pending","approved","matched"].includes(r.status));if(duplicate){toast("Request already exists","Your verification request is already on record.","error");return}requests.unshift({id:uid("REQ"),village,name,phone,memberNo,note,status:"pending",createdAt:now()});write(KEYS.requests,requests);e.target.reset();toast("Request submitted","Admin will verify your name against the register.")}
function generatedId(v){const prefix=v.replace(/[^A-Za-z]/g,"").slice(0,2).toUpperCase();let n=read(KEYS.members).filter(m=>m.village===v).length+1;let id=`${prefix}-${String(n).padStart(4,"0")}`;while(read(KEYS.members).some(m=>m.id===id))id=`${prefix}-${String(++n).padStart(4,"0")}`;return id}
function generatePassword(){return `UL-${Math.random().toString(36).slice(2,8).toUpperCase()}`}
function verifyRequest(id){const req=read(KEYS.requests).find(r=>r.id===id);if(!req)return;const members=read(KEYS.members);if(members.some(m=>m.village===req.village&&norm(m.name)===norm(req.name))){toast("Duplicate blocked","This registered name already has a login. No second login was created.","error");return}const member={id:generatedId(req.village),name:req.name,phone:req.phone,village:req.village,password:generatePassword(),active:true,verified:true,createdAt:now()};members.push(member);write(KEYS.members,members);const rs=read(KEYS.requests);const r=rs.find(x=>x.id===id);r.status="approved";r.approvedAt=now();r.approvedBy=session()?.name||MASTER.name;r.generatedMemberId=member.id;write(KEYS.requests,rs);audit("Member verification",`Verified ${member.name} and generated member credentials`,{memberId:member.id});renderAdmin();toast("Member verified",`${member.id} / ${member.password}`)}
function rejectRequest(id){const rs=read(KEYS.requests),r=rs.find(x=>x.id===id);if(!r)return;r.status="rejected";r.rejectedAt=now();r.rejectedBy=session()?.name||MASTER.name;write(KEYS.requests,rs);audit("Member request rejected",`Rejected ${r.name}`,{requestId:id});renderAdmin();toast("Request rejected","The request was rejected.")}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(file)})}
async function submitPayment(e){e.preventDefault();const s=session();if(!s||s.role!=="member")return;const type=$("#contributionType").value,amount=Number($("#contributionAmount").value),date=$("#paymentDate").value,file=$("#paymentProof").files[0];if(!type||amount<=0||!date||!file){toast("Incomplete payment","Select levy, amount, date and proof.","error");return}if(file.size>2*1024*1024){toast("File too large","For this demo, keep proof files below 2 MB.","error");return}let proofData="";try{proofData=await fileToDataURL(file)}catch(_){toast("Upload failed","The browser could not read the file.","error");return}const rows=read(KEYS.transactions);rows.unshift({id:uid("TX"),memberId:s.id,memberName:s.name,village:s.village,type,amount,paymentDate:date,proofName:file.name,proofSize:file.size,proofType:file.type,proofData,status:"pending",submittedAt:now()});write(KEYS.transactions,rows);toast("Payment submitted","Admin can open the uploaded proof before verification.");renderMember()}
function approveTx(id,ok=true){const rows=read(KEYS.transactions),x=rows.find(r=>r.id===id);if(!x)return;x.status=ok?"verified":"rejected";x.reviewedAt=now();x.reviewedBy=session()?.name||MASTER.name;write(KEYS.transactions,rows);audit(ok?"Payment verified":"Payment rejected",`${x.type} ${ok?"verified":"rejected"} for ${x.memberName}`,{transactionId:id,memberId:x.memberId});renderAdmin();toast(ok?"Payment verified":"Payment rejected",`${x.memberName} · ${x.type}`)}
function markPresent(){const s=session();if(!s)return;const d=new Date().toISOString().slice(0,10),rows=read(KEYS.attendance);if(rows.some(x=>x.memberId===s.id&&x.date===d)){toast("Already submitted","Attendance for today is already recorded.","error");return}rows.unshift({id:uid("ATT"),memberId:s.id,memberName:s.name,village:s.village,date:d,status:"pending",submittedAt:now()});write(KEYS.attendance,rows);renderMember();toast("Attendance submitted","Admin will compare it with the physical register.")}
function reviewAttendance(id,ok=true){const rows=read(KEYS.attendance),x=rows.find(r=>r.id===id);if(!x)return;x.status=ok?"approved":"rejected";x.reviewedAt=now();x.reviewedBy=session()?.name||MASTER.name;write(KEYS.attendance,rows);audit(ok?"Attendance approved":"Attendance rejected",`${x.memberName} attendance ${ok?"approved":"rejected"}`,{attendanceId:id,memberId:x.memberId});renderAdmin();toast(ok?"Attendance approved":"Attendance rejected",x.memberName)}
function addExpense(e){e.preventDefault();const s=session();if(!s||s.role!=="admin")return;const desc=$("#expenseDescription").value.trim(),amount=Number($("#expenseAmount").value),date=$("#expenseDate").value,category=$("#expenseCategory").value.trim()||"General Expense";if(!desc||amount<=0||!date){toast("Incomplete expense","Enter description, amount and date.","error");return}const rows=read(KEYS.expenses);rows.unshift({id:uid("EXP"),village:s.village,description:desc,category,amount,date,createdBy:s.name,createdAt:now()});write(KEYS.expenses,rows);audit("Expense recorded",`${desc} · ${money(amount)}`,{expenseId:rows[0].id});renderAdminView("expenses");toast("Expense recorded","It is now included in monthly and annual reports.")}
function saveLevy(e){e.preventDefault();const id=$("#levyId").value,name=$("#levyName").value.trim(),amount=Number($("#levyAmount").value)||0,mandatory=$("#levyMandatory").checked;if(!name){toast("Levy name required","Enter a levy name.","error");return}let rows=read(KEYS.levies,DEFAULT_LEVIES);if(id){const x=rows.find(r=>r.id===id);if(x){x.name=name;x.amount=amount;x.mandatory=mandatory;x.active=true}}else rows.push({id:uid("LEV"),name,amount,mandatory,active:true});write(KEYS.levies,rows);audit("Levy settings changed",`${name} · ${money(amount)} · ${mandatory?"Mandatory":"Optional"}`);renderAdminView("levies");toast("Levy saved","Member outstanding bills use the updated levy settings.")}
function removeLevy(id){const rows=read(KEYS.levies),x=rows.find(r=>r.id===id);if(!x)return;x.active=false;write(KEYS.levies,rows);audit("Levy removed",`Disabled ${x.name}`);renderAdminView("levies");toast("Levy removed","The levy is no longer shown for new obligations.")}
function editLevy(id){const x=read(KEYS.levies,DEFAULT_LEVIES).find(r=>r.id===id);if(!x)return;$("#levyId").value=x.id;$("#levyName").value=x.name;$("#levyAmount").value=x.amount;$("#levyMandatory").checked=x.mandatory;window.scrollTo(0,0)}
function assignAdmin(e){e.preventDefault();const s=session();if(!s?.master){toast("Permission denied","Only the master administrator can assign village administrators.","error");return}const member=read(KEYS.members).find(m=>m.id===$("#assignMember").value);if(!member)return;const admins=read(KEYS.admins);if(admins.some(a=>a.memberId===member.id)){toast("Already assigned","This member already has an administrator login.","error");return}const a={id:`ADM-${member.id}`,password:generatePassword(),name:member.name,role:"admin",village:member.village,memberId:member.id,master:false,active:true,createdAt:now()};admins.push(a);write(KEYS.admins,admins);audit("Administrator assigned",`${member.name} assigned as village administrator`,{assignedAdminId:a.id});renderAdminView("admins");toast("Administrator assigned",`${a.name} · ${a.id} / ${a.password}`)}
function toggleAdmin(id){const rows=read(KEYS.admins),x=rows.find(a=>a.id===id);if(!x||x.master)return;x.active=!x.active;write(KEYS.admins,rows);audit(x.active?"Administrator enabled":"Administrator disabled",`${x.name} · ${x.village}`);renderAdminView("admins")}
function verifiedTx(v){return read(KEYS.transactions).filter(x=>x.status==="verified"&&(!v||x.village===v))}
function expenses(v){return read(KEYS.expenses).filter(x=>!v||x.village===v)}
function reportData(v,year=null,month=null){const income=verifiedTx(v).filter(x=>!year||String(new Date(x.paymentDate).getFullYear())===String(year)).filter(x=>month==null||new Date(x.paymentDate).getMonth()===month);const exp=expenses(v).filter(x=>!year||String(new Date(x.date).getFullYear())===String(year)).filter(x=>month==null||new Date(x.date).getMonth()===month);const inc=income.reduce((a,x)=>a+Number(x.amount||0),0),out=exp.reduce((a,x)=>a+Number(x.amount||0),0);return {income,exp,inc,out,net:inc-out}}
function printReport(v,year=new Date().getFullYear(),month=null,memberId=null){let d=reportData(v,year,month);let member=null;if(memberId){member=read(KEYS.members).find(m=>m.id===memberId&&m.village===v);if(!member){toast("Access denied","That member does not belong to this village.","error");return}d.income=d.income.filter(x=>x.memberId===memberId)}const title=memberId?`Member Financial Statement — ${member?.name||memberId}`:`${v||"All Villages"} Financial Report`;const w=window.open("","_blank","width=900,height=700");if(!w){toast("Popup blocked","Allow popups to generate the report.","error");return}const levies=activeLevy();w.document.write(`<html><head><title>${esc(title)}</title><style>body{font-family:Arial;padding:35px;color:#071711}h1{color:#8b6f2d}table{width:100%;border-collapse:collapse;margin:20px 0}th,td{border:1px solid #ddd;padding:9px;text-align:left}button{padding:10px 15px}@media print{button{display:none}}</style></head><body><h1>UNIONLEDGER</h1><h2>${esc(title)}</h2><p>Generated ${esc(dateTime(now()))}</p>${memberId?`<h3>Annual Mandatory Obligations</h3><table><tr><th>Levy</th><th>Required</th><th>Paid</th><th>Outstanding</th></tr>${memberObligations(member).map(o=>`<tr><td>${esc(o.levy.name)}</td><td>${money(o.levy.amount)}</td><td>${money(o.paid)}</td><td>${money(o.balance)}</td></tr>`).join("")||'<tr><td colspan="4">No mandatory annual levies.</td></tr>'}</table>`:""}<table><tr><th>Income</th><th>Amount</th></tr>${levies.map(l=>`<tr><td>${esc(l.name)}</td><td>${money(d.income.filter(x=>x.type===l.name).reduce((a,x)=>a+Number(x.amount||0),0))}</td></tr>`).join("")}<tr><th>Total Income</th><th>${money(d.inc)}</th></tr></table>${memberId?"":`<h3>Expenses</h3><table><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th></tr>${d.exp.map(x=>`<tr><td>${dateOnly(x.date)}</td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td>${money(x.amount)}</td></tr>`).join("")||'<tr><td colspan="4">No expenses</td></tr>'}<tr><th colspan="3">Total Expenses</th><th>${money(d.out)}</th></tr><tr><th colspan="3">Net Position</th><th>${money(d.net)}</th></tr></table>`}<button onclick="window.print()">Print / Save as PDF</button></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
function memberObligations(member){const year=new Date().getFullYear(),tx=read(KEYS.transactions).filter(x=>x.memberId===member.id&&x.status==="verified"&&new Date(x.paymentDate).getFullYear()===year),levies=activeLevy().filter(l=>l.mandatory),paidBy={};levies.forEach(l=>paidBy[l.name]=tx.filter(x=>x.type===l.name).reduce((a,x)=>a+Number(x.amount||0),0));return levies.map(l=>({levy:l,paid:paidBy[l.name]||0,balance:Math.max(0,l.amount-(paidBy[l.name]||0))})).filter(x=>x.levy.amount>0)}
function renderMember(){const s=session();if(!s||s.role!=="member")return;$("#appRoot").innerHTML=`<div class="app-shell"><div class="app-top"><div><span class="eyebrow">Member Portal</span><h2>${esc(s.name)}</h2><p>${esc(s.village)} · ${esc(s.id)}</p></div><button class="btn btn-ghost" data-action="logout">Sign out</button></div><div class="app-tabs"><button class="app-tab active" data-app-tab="overview">Overview</button><button class="app-tab" data-app-tab="payments">Submit Payment</button><button class="app-tab" data-app-tab="attendance">Attendance</button><button class="app-tab" data-app-tab="records">My Financial Records</button></div><div id="memberView"></div></div>`;renderMemberView("overview")}
function renderMemberView(tab){const s=session(),tx=read(KEYS.transactions).filter(x=>x.memberId===s.id),att=read(KEYS.attendance).filter(x=>x.memberId===s.id),ob=memberObligations(read(KEYS.members).find(m=>m.id===s.id)||{}),paid=tx.filter(x=>x.status==="verified").reduce((a,x)=>a+Number(x.amount||0),0),out=ob.reduce((a,x)=>a+x.balance,0),root=$("#memberView");if(!root)return;
 if(tab==="overview")root.innerHTML=`<div class="stat-grid"><div class="app-stat"><span>Verified paid this year</span><strong>${money(paid)}</strong></div><div class="app-stat"><span>Mandatory outstanding</span><strong>${money(out)}</strong></div><div class="app-stat"><span>Approved attendance</span><strong>${att.filter(x=>x.status==="approved").length}</strong></div></div><div class="app-card"><div class="card-head"><div><h3>My annual obligations</h3><p>Mandatory levies are shown here so you can see what remains unpaid.</p></div><button class="btn btn-outline" data-action="member-report">Download statement</button></div><div class="table-wrap"><table><tr><th>Levy</th><th>Required</th><th>Paid</th><th>Outstanding</th><th>Status</th></tr>${ob.map(x=>`<tr><td>${esc(x.levy.name)}</td><td>${money(x.levy.amount)}</td><td>${money(x.paid)}</td><td>${money(x.balance)}</td><td><span class="badge ${x.balance?"pending":"approved"}">${x.balance?"Outstanding":"Up to date"}</span></td></tr>`).join("")||'<tr><td colspan="5">No mandatory annual levies are currently configured.</td></tr>'}</table></div></div><div class="app-card"><div class="action-grid"><button class="action-btn" data-app-tab="payments">＋ Submit payment proof</button><button class="action-btn" data-action="mark-attendance">✓ Mark present today</button><button class="action-btn" data-app-tab="attendance">◷ Attendance history</button><button class="action-btn" data-app-tab="records">▣ Financial history</button></div></div>`;
 if(tab==="payments")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Submit payment proof</h3><p>Admin must inspect and verify your uploaded document.</p></div></div><form id="paymentForm" class="app-form"><label>Levy / contribution<select id="contributionType" required><option value="">Select type</option>${activeLevy().map(x=>`<option>${esc(x.name)}</option>`).join("")}</select></label><label>Amount (₦)<input id="contributionAmount" type="number" min="1" step="0.01" required></label><label>Payment date<input id="paymentDate" type="date" required></label><label>Payment proof<input id="paymentProof" type="file" accept="image/*,.pdf" required></label><button class="btn btn-primary">Submit for verification</button></form></div>`;
 if(tab==="attendance")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Attendance history</h3><p>Only your attendance records are shown.</p></div><button class="btn btn-primary" data-action="mark-attendance">Mark Present Today</button></div><div class="table-wrap"><table><tr><th>Date</th><th>Status</th><th>Reviewed by</th><th>Timestamp</th></tr>${att.map(x=>`<tr><td>${dateOnly(x.date)}</td><td><span class="badge ${x.status}">${esc(x.status)}</span></td><td>${esc(x.reviewedBy||"—")}</td><td>${x.reviewedAt?dateTime(x.reviewedAt):"—"}</td></tr>`).join("")||'<tr><td colspan="4">No attendance records yet.</td></tr>'}</table></div></div>`;
 if(tab==="records")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>My financial records</h3><p>Only your own records are visible.</p></div><button class="btn btn-outline" data-action="member-report">Download statement</button></div><div class="table-wrap"><table><tr><th>Date</th><th>Type</th><th>Amount</th><th>Status</th><th>Proof</th></tr>${tx.map(x=>`<tr><td>${dateOnly(x.paymentDate)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td><span class="badge ${x.status}">${esc(x.status)}</span></td><td>${esc(x.proofName||"—")}</td></tr>`).join("")||'<tr><td colspan="5">No financial records yet.</td></tr>'}</table></div></div>`}
function adminScopeRows(rows){const s=session();return rows.filter(x=>s?.master||x.village===s?.village)}
function renderAdmin(){const s=session();if(!s||s.role!=="admin")return;const req=adminScopeRows(read(KEYS.requests)).filter(x=>["pending","matched"].includes(x.status)),pay=adminScopeRows(read(KEYS.transactions)).filter(x=>x.status==="pending"),att=adminScopeRows(read(KEYS.attendance)).filter(x=>x.status==="pending"),members=read(KEYS.members).filter(m=>s.master||m.village===s.village);$("#appRoot").innerHTML=`<div class="app-shell"><div class="app-top"><div><span class="eyebrow">Administrator Portal</span><h2>${esc(s.name)}</h2><p>${esc(s.village)} · ${s.master?"Master administrator":"Village administrator"}</p></div><button class="btn btn-ghost" data-action="logout">Sign out</button></div><div class="admin-summary"><div class="app-stat"><span>Members</span><strong>${members.length}</strong></div><div class="app-stat"><span>Pending payments</span><strong>${pay.length}</strong></div><div class="app-stat"><span>Pending attendance</span><strong>${att.length}</strong></div><div class="app-stat"><span>Outstanding mandatory bills</span><strong>${money(members.reduce((a,m)=>a+memberObligations(m).reduce((z,x)=>z+x.balance,0),0))}</strong></div></div><div class="app-tabs"><button class="app-tab active" data-admin-tab="requests">Requests (${req.length})</button><button class="app-tab" data-admin-tab="payments">Payments (${pay.length})</button><button class="app-tab" data-admin-tab="attendance">Attendance (${att.length})</button><button class="app-tab" data-admin-tab="register">Members Register</button><button class="app-tab" data-admin-tab="expenses">Expenses</button><button class="app-tab" data-admin-tab="levies">Levies</button><button class="app-tab" data-admin-tab="reports">Reports</button><button class="app-tab" data-admin-tab="admins">Admin Duties</button><button class="app-tab" data-admin-tab="audit">Audit</button></div><div id="adminView"></div></div>`;renderAdminView("requests")}
function memberRecord(id){const s=session(),m=read(KEYS.members).find(x=>x.id===id);if(!m||(!s?.master&&m.village!==s?.village)){toast("Access denied","You cannot open another village's member record.","error");return}const tx=read(KEYS.transactions).filter(x=>x.memberId===id),att=read(KEYS.attendance).filter(x=>x.memberId===id),ob=memberObligations(m);$("#adminView").innerHTML=`<div class="app-card"><div class="card-head"><div><h3>${esc(m.name)}</h3><p>${esc(m.village)} · ${esc(m.id)} · ${esc(m.phone)}</p></div><div class="record-actions"><button class="btn btn-outline" data-action="member-report-admin" data-id="${m.id}">Download breakdown</button><button class="btn btn-outline" data-admin-tab="register">← Register</button></div></div><div class="credential-box"><strong>Generated login details</strong><span>Member ID: <b>${esc(m.id)}</b></span><span>Password: <b>${esc(m.password||"Not generated")}</b></span><small>Admin-only view. Do not publish credentials.</small></div><div class="stat-grid"><div class="app-stat"><span>Mandatory outstanding</span><strong>${money(ob.reduce((a,x)=>a+x.balance,0))}</strong></div><div class="app-stat"><span>Verified paid</span><strong>${money(tx.filter(x=>x.status==="verified").reduce((a,x)=>a+Number(x.amount||0),0))}</strong></div><div class="app-stat"><span>Approved attendance</span><strong>${att.filter(x=>x.status==="approved").length}</strong></div></div><h4>Annual obligations</h4><div class="table-wrap"><table><tr><th>Levy</th><th>Required</th><th>Paid</th><th>Balance</th></tr>${ob.map(x=>`<tr><td>${esc(x.levy.name)}</td><td>${money(x.levy.amount)}</td><td>${money(x.paid)}</td><td>${money(x.balance)}</td></tr>`).join("")||'<tr><td colspan="4">No mandatory levies.</td></tr>'}</table></div><h4>Attendance — editable</h4><div class="table-wrap"><table><tr><th>Date</th><th>Status</th><th>Reviewed by</th><th>Timestamp</th><th>Edit</th></tr>${att.map(x=>`<tr><td>${dateOnly(x.date)}</td><td><span class="badge ${x.status}">${esc(x.status)}</span></td><td>${esc(x.reviewedBy||"—")}</td><td>${x.reviewedAt?dateTime(x.reviewedAt):"—"}</td><td><button class="mini-btn" data-action="edit-attendance" data-id="${x.id}">Edit</button></td></tr>`).join("")||'<tr><td colspan="5">No attendance.</td></tr>'}</table></div><h4>Financial records — editable</h4><div class="table-wrap"><table><tr><th>Date</th><th>Type</th><th>Amount</th><th>Status</th><th>Proof</th><th>Edit</th></tr>${tx.map(x=>`<tr><td>${dateOnly(x.paymentDate)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td><td>${x.proofData?`<button class="mini-btn" data-action="view-proof" data-id="${x.id}">View document</button>`:esc(x.proofName||"—")}</td><td><button class="mini-btn" data-action="edit-transaction" data-id="${x.id}">Edit</button></td></tr>`).join("")||'<tr><td colspan="6">No financial records.</td></tr>'}</table></div></div>`}
function editAttendance(id){const s=session(),rows=read(KEYS.attendance),x=rows.find(a=>a.id===id);if(!x||(!s?.master&&x.village!==s?.village))return;const next=prompt("Set attendance status: approved, absent, pending, or rejected",x.status||"approved");if(!next||!["approved","absent","pending","rejected"].includes(next.toLowerCase())){toast("Invalid status","Use approved, absent, pending or rejected.","error");return}x.status=next.toLowerCase();x.reviewedAt=now();x.reviewedBy=s.name;write(KEYS.attendance,rows);audit("Attendance edited",`${x.memberName} attendance changed to ${x.status}`,{attendanceId:id,memberId:x.memberId});memberRecord(x.memberId);toast("Attendance updated",`${x.memberName} · ${x.status}`)}
function editTransaction(id){const s=session(),rows=read(KEYS.transactions),x=rows.find(t=>t.id===id);if(!x||(!s?.master&&x.village!==s?.village))return;const amount=Number(prompt("Amount (₦)",x.amount));if(!(amount>0)){toast("Invalid amount","Amount must be greater than zero.","error");return}const type=prompt("Contribution / levy type",x.type);if(!type)return;const status=prompt("Status: verified, pending, rejected",x.status);if(!["verified","pending","rejected"].includes(String(status).toLowerCase())){toast("Invalid status","Use verified, pending or rejected.","error");return}x.amount=amount;x.type=type.trim();x.status=String(status).toLowerCase();x.reviewedAt=now();x.reviewedBy=s.name;write(KEYS.transactions,rows);audit("Financial record edited",`${x.memberName} · ${x.type} · ${money(x.amount)} · ${x.status}`,{transactionId:id,memberId:x.memberId});memberRecord(x.memberId);toast("Financial record updated",x.memberName)}
function renderAdminView(tab){const root=$("#adminView"),s=session();if(!root||!s)return;const req=adminScopeRows(read(KEYS.requests)),tx=adminScopeRows(read(KEYS.transactions)),att=adminScopeRows(read(KEYS.attendance)),members=read(KEYS.members).filter(m=>s.master||m.village===s.village),ex=adminScopeRows(read(KEYS.expenses));
 if(tab==="requests")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Member verification requests</h3><p>Cross-check every request against the register before issuing one unique login.</p></div></div><div class="table-wrap"><table><tr><th>Name</th><th>Village</th><th>Phone</th><th>Status</th><th>Action</th></tr>${req.filter(x=>["pending","matched"].includes(x.status)).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.village)}</td><td>${esc(x.phone)}</td><td>${esc(x.status)}</td><td><button class="mini-btn" data-action="verify-request" data-id="${x.id}">Verify & Generate</button> <button class="mini-btn danger" data-action="reject-request" data-id="${x.id}">Reject</button></td></tr>`).join("")||'<tr><td colspan="5">No pending requests.</td></tr>'}</table></div></div>`;
 if(tab==="payments")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Payment verification</h3><p>Open the actual uploaded document before approval.</p></div></div><div class="table-wrap"><table><tr><th>Member</th><th>Type</th><th>Amount</th><th>Proof</th><th>Action</th></tr>${tx.filter(x=>x.status==="pending").map(x=>`<tr><td>${esc(x.memberName)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${x.proofData?`<button class="mini-btn" data-action="view-proof" data-id="${x.id}">View document</button>`:esc(x.proofName)}</td><td><button class="mini-btn" data-action="approve-tx" data-id="${x.id}">Approve</button> <button class="mini-btn danger" data-action="reject-tx" data-id="${x.id}">Reject</button></td></tr>`).join("")||'<tr><td colspan="5">No pending payments.</td></tr>'}</table></div></div>`;
 if(tab==="attendance")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Attendance verification</h3><p>Compare with the manual register.</p></div></div><div class="table-wrap"><table><tr><th>Member</th><th>Village</th><th>Date</th><th>Action</th></tr>${att.filter(x=>x.status==="pending").map(x=>`<tr><td>${esc(x.memberName)}</td><td>${esc(x.village)}</td><td>${dateOnly(x.date)}</td><td><button class="mini-btn" data-action="approve-att" data-id="${x.id}">Approve</button> <button class="mini-btn danger" data-action="reject-att" data-id="${x.id}">Reject</button></td></tr>`).join("")||'<tr><td colspan="4">No pending attendance.</td></tr>'}</table></div></div>`;
 if(tab==="register")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Members Register</h3><p>Click a member to inspect and edit their attendance and financial history.</p></div></div><div class="table-wrap"><table><tr><th>Member</th><th>Village</th><th>Login ID</th><th>Attendance</th><th>Paid</th><th>Outstanding</th><th>Action</th></tr>${members.map(m=>{const paid=read(KEYS.transactions).filter(x=>x.memberId===m.id&&x.status==="verified").reduce((a,x)=>a+Number(x.amount||0),0),out=memberObligations(m).reduce((a,x)=>a+x.balance,0);return `<tr><td>${esc(m.name)}</td><td>${esc(m.village)}</td><td>${esc(m.id)}</td><td>${read(KEYS.attendance).filter(x=>x.memberId===m.id&&x.status==="approved").length}</td><td>${money(paid)}</td><td>${money(out)}</td><td><button class="mini-btn" data-action="open-member" data-id="${m.id}">Open record</button></td></tr>`}).join("")}</table></div></div>`;
 if(tab==="expenses")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Expenses / Expenditure</h3><p>Every expense is included in the same monthly and annual report totals.</p></div></div><form id="expenseForm" class="app-form inline-form"><label>Description<input id="expenseDescription" required></label><label>Category<input id="expenseCategory" placeholder="e.g. Hall, transport, stationery"></label><label>Amount (₦)<input id="expenseAmount" type="number" min="1" step="0.01" required></label><label>Date<input id="expenseDate" type="date" required></label><button class="btn btn-primary">Record expense</button></form><div class="table-wrap"><table><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Recorded by</th></tr>${ex.map(x=>`<tr><td>${dateOnly(x.date)}</td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td>${money(x.amount)}</td><td>${esc(x.createdBy)}</td></tr>`).join("")||'<tr><td colspan="5">No expenses recorded.</td></tr>'}</table></div></div>`;
 if(tab==="levies"){const lev=read(KEYS.levies,DEFAULT_LEVIES).filter(x=>x.active);root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Levies & annual obligations</h3><p>Add, edit, disable and mark mandatory annual levies.</p></div></div><form id="levyForm" class="app-form inline-form"><input id="levyId" type="hidden"><label>Levy name<input id="levyName" required></label><label>Amount (₦)<input id="levyAmount" type="number" min="0" step="0.01" required></label><label class="check-row"><input id="levyMandatory" type="checkbox"> Mandatory annually</label><button class="btn btn-primary">Save levy</button></form><div class="table-wrap"><table><tr><th>Levy</th><th>Amount</th><th>Mandatory</th><th>Action</th></tr>${lev.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.amount)}</td><td>${x.mandatory?"Yes":"No"}</td><td><button class="mini-btn" data-action="edit-levy" data-id="${x.id}">Edit</button> <button class="mini-btn danger" data-action="remove-levy" data-id="${x.id}">Remove</button></td></tr>`).join("")}</table></div></div>`}
 if(tab==="admins"){const admins=read(KEYS.admins).filter(a=>s.master||a.village===s.village),available=members.filter(m=>!read(KEYS.admins).some(a=>a.memberId===m.id));root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Admin duty assignment</h3><p>Assigned members receive a village-scoped admin login. Their actual names are used in every audit timestamp.</p></div></div>${s.master?`<form id="assignAdminForm" class="app-form inline-form"><label>Member<select id="assignMember" required><option value="">Select member</option>${available.map(m=>`<option value="${m.id}">${esc(m.name)} · ${esc(m.village)}</option>`).join("")}</select></label><button class="btn btn-primary">Assign admin duty</button></form>`:"<p class='notice'>Only the master administrator can assign new administrators.</p>"}<div class="table-wrap"><table><tr><th>Name</th><th>Admin ID</th><th>Village</th><th>Status</th><th>Login credentials</th><th>Action</th></tr>${admins.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.id)}</td><td>${esc(a.village)}</td><td>${a.active?"Active":"Disabled"}</td><td><strong>${esc(a.id)}</strong> / <strong>${esc(a.password)}</strong></td><td>${a.master?"Master":`<button class="mini-btn" data-action="toggle-admin" data-id="${a.id}">${a.active?"Disable":"Enable"}</button>`}</td></tr>`).join("")}</table></div></div>`}
 if(tab==="reports")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Monthly / Annual Accounting Reports</h3><p>Income minus expenses. Expenses are included in the same report.</p></div></div><div class="app-form inline-form"><label>Year<input id="reportYear" type="number" value="${new Date().getFullYear()}"></label><label>Month<select id="reportMonth"><option value="">Annual</option>${Array.from({length:12},(_,i)=>`<option value="${i}">${new Date(2000,i,1).toLocaleString("en-NG",{month:"long"})}</option>`).join("")}</select></label><button class="btn btn-primary" data-action="generate-report">Generate PDF</button></div><div class="stat-grid"><div class="app-stat"><span>Verified income</span><strong id="reportIncome">—</strong></div><div class="app-stat"><span>Expenses</span><strong id="reportExpense">—</strong></div><div class="app-stat"><span>Net position</span><strong id="reportNet">—</strong></div></div></div>`;updateReportPreview();
 if(tab==="audit")root.innerHTML=`<div class="app-card"><div class="card-head"><div><h3>Administrative audit trail</h3><p>Actual administrator names and timestamps are retained.</p></div></div><div class="table-wrap"><table><tr><th>Time</th><th>Admin</th><th>Village</th><th>Action</th><th>Detail</th></tr>${adminScopeRows(read(KEYS.audit)).slice(0,150).map(x=>`<tr><td>${dateTime(x.at)}</td><td>${esc(x.adminName)}</td><td>${esc(x.village||"—")}</td><td>${esc(x.action)}</td><td>${esc(x.detail)}</td></tr>`).join("")||'<tr><td colspan="5">No audit events.</td></tr>'}</table></div></div>`}
function updateReportPreview(){const y=Number($("#reportYear")?.value)||new Date().getFullYear(),m=$("#reportMonth")?.value;const d=reportData(session().master?null:session().village,y,m===""?null:Number(m));if($("#reportIncome"))$("#reportIncome").textContent=money(d.inc);if($("#reportExpense"))$("#reportExpense").textContent=money(d.out);if($("#reportNet"))$("#reportNet").textContent=money(d.net)}
function viewProof(id){const x=read(KEYS.transactions).find(t=>t.id===id);if(!x?.proofData){toast("Document unavailable","No document data is stored for this record.","error");return}const w=window.open("","_blank","width=900,height=700");if(!w){toast("Popup blocked","Allow popups to view the document.","error");return}if(x.proofType?.startsWith("image/"))w.document.write(`<title>${esc(x.proofName)}</title><body style="margin:0;background:#111;display:grid;place-items:center"><img src="${x.proofData}" style="max-width:100%;max-height:100vh"></body>`);else w.location.href=x.proofData}
function delegate(e){const b=e.target.closest("[data-login]");if(b){e.preventDefault();openAuth(b.dataset.login);return}const s=e.target.closest("[data-scroll]");if(s){e.preventDefault();document.getElementById(s.dataset.scroll)?.scrollIntoView({behavior:"smooth"});return}if(e.target.closest("[data-close-modal]")){closeAuth();return}if(e.target.closest("[data-close-app]")){closeApp();return}const at=e.target.closest("[data-auth-tab]");if(at){setAuthTab(at.dataset.authTab);return}const mt=e.target.closest("[data-app-tab]");if(mt&&session()?.role==="member"){$$('[data-app-tab]').forEach(x=>x.classList.toggle("active",x.dataset.appTab===mt.dataset.appTab));renderMemberView(mt.dataset.appTab);return}const ad=e.target.closest("[data-admin-tab]");if(ad&&session()?.role==="admin"){$$('[data-admin-tab]').forEach(x=>x.classList.toggle("active",x.dataset.adminTab===ad.dataset.adminTab));renderAdminView(ad.dataset.adminTab);return}const a=e.target.closest("[data-action]");if(!a)return;const id=a.dataset.id;switch(a.dataset.action){case"logout":setSession(null);closeApp();break;case"mark-attendance":markPresent();break;case"verify-request":verifyRequest(id);break;case"reject-request":rejectRequest(id);break;case"approve-tx":approveTx(id,true);break;case"reject-tx":approveTx(id,false);break;case"approve-att":reviewAttendance(id,true);break;case"reject-att":reviewAttendance(id,false);break;case"view-proof":viewProof(id);break;case"open-member":memberRecord(id);break;case"edit-attendance":editAttendance(id);break;case"edit-transaction":editTransaction(id);break;case"member-report":printReport(session().village,new Date().getFullYear(),null,session().id);break;case"member-report-admin":printReport(session().village,new Date().getFullYear(),null,id);break;case"edit-levy":editLevy(id);break;case"remove-levy":removeLevy(id);break;case"toggle-admin":toggleAdmin(id);break;case"generate-report":{const y=Number($("#reportYear").value)||new Date().getFullYear(),m=$("#reportMonth").value;printReport(session().master?null:session().village,y,m===""?null:Number(m));break}}
}
function init(){seed();fillVillages();document.addEventListener("click",delegate);$("#loginForm")?.addEventListener("submit",login);$("#registerForm")?.addEventListener("submit",registerMember);document.addEventListener("submit",e=>{if(e.target?.id==="paymentForm")submitPayment(e);if(e.target?.id==="expenseForm")addExpense(e);if(e.target?.id==="levyForm")saveLevy(e);if(e.target?.id==="assignAdminForm")assignAdmin(e)});$("#showRegister")?.addEventListener("click",e=>{e.preventDefault();setAuthTab("register")});$("#showLogin")?.addEventListener("click",e=>{e.preventDefault();setAuthTab("login")});$("#togglePassword")?.addEventListener("click",()=>{const x=$("#loginPassword");if(x)x.type=x.type==="password"?"text":"password"});$("#forgotPassword")?.addEventListener("click",e=>{e.preventDefault();toast("Password reset","Contact the union administrator to issue a new credential.")});$("#mobileMenuButton")?.addEventListener("click",()=>$("#mobileMenu")?.classList.toggle("open"));$("#demoReportBtn")?.addEventListener("click",()=>printReport("Obodo Union",new Date().getFullYear()));$("#chartFilter")?.addEventListener("change",e=>toast("Chart updated",e.target.options[e.target.selectedIndex].text));$("#authModal")?.addEventListener("click",e=>{if(e.target.id==="authModal")closeAuth()});$("#appModal")?.addEventListener("click",e=>{if(e.target.id==="appModal")closeApp()});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
